Repository HunterPie/HunterPie, pull requests merged in 2022-10, with the labels that each got.

#223 Feat(UI): Add GitHub button
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Domain/Sidebar/DefaultSideBar.cs
  HunterPie/GUI/Parts/Sidebar/ViewModels/GithubSideBarElementViewModel.cs
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: UI

#225 Fix(UI): Fix IS_WIREBUG_BLOCKED_OFFSETS
  HunterPie/Address/MonsterHunterRise.12.0.0.0.map
Labels: bug

#231 Docs: Added account docs
  Docs/_posts/2022-10-10-account.md
  Docs/_posts/2022-10-10-saves-backup.md
Labels: documentation

#230 Feat(UI|Core): Add backup feature
  HunterPie.Core/API/Entities/BackupDeleteResponse.cs
  HunterPie.Core/API/Entities/BackupResponse.cs
  HunterPie.Core/API/Entities/ErrorCode.cs
  HunterPie.Core/API/Entities/GameType.cs
  HunterPie.Core/API/Entities/UserBackupDetailsResponse.cs
  HunterPie.Core/API/PoogieApi.cs
  HunterPie.Core/Client/ClientInfo.cs
  HunterPie.Core/Domain/Constants/FeatureFlags.cs
  HunterPie.Core/Extensions/DateTimeExtensions.cs
  HunterPie.Core/Http/Poogie.cs
  HunterPie.Core/Http/PoogieBuilder.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Core/Zip/CompressionProvider.cs
  HunterPie.UI/Architecture/Converters/PercentageToRelativeSizeConverter.cs
  HunterPie.UI/Architecture/Dispatchers/DispatcherJob.cs
  HunterPie.UI/Architecture/View.cs
  HunterPie.UI/Architecture/ViewModel.cs
  HunterPie.UI/Controls/Image/Icon.xaml
  HunterPie.UI/Controls/Image/Icon.xaml.cs
  HunterPie.UI/Controls/Notfication/Push.xaml
  HunterPie.UI/Controls/Notfication/Push.xaml.cs
  HunterPie.UI/Controls/TextBox/SearchTextBox.xaml
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/HunterPie.UI.csproj.user
  HunterPie.UI/Resources/Colors.xaml
  HunterPie.UI/Resources/Icons.xaml
  HunterPie/App.xaml.cs
  HunterPie/Features/Account/Config/AccountConfig.cs
  HunterPie/Features/Account/Config/LocalAccountConfig.cs
  HunterPie/Features/Backups/GameSaveBackupService.cs
  HunterPie/Features/Backups/Games/MHRBackupService.cs
  HunterPie/Features/Backups/Games/MHWBackupService.cs
  HunterPie/Features/Backups/IBackupService.cs
  HunterPie/Features/ContextInitializers.cs
  HunterPie/Features/DefaultFeatureFlags.cs
  HunterPie/Features/Notification/AppNotificationManager.cs
  HunterPie/GUI/Parts/Account/Views/AccountPreferencesView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountView.xaml.cs
  HunterPie/GUI/Parts/Backup/ViewModels/BackupElementViewModel.cs
  HunterPie/GUI/Parts/Backup/ViewModels/BackupsViewModel.cs
  HunterPie/GUI/Parts/Backup/Views/BackupElementView.xaml
  HunterPie/GUI/Parts/Backup/Views/BackupElementView.xaml.cs
  HunterPie/GUI/Parts/Backup/Views/BackupsView.xaml
  HunterPie/GUI/Parts/Backup/Views/BackupsView.xaml.cs
  HunterPie/GUI/Parts/HeaderBar.xaml
  HunterPie/GUI/Parts/HeaderBar.xaml.cs
  HunterPie/GUI/Parts/Sidebar/ViewModels/SettingsSideBarElementViewModel.cs
  HunterPie/HunterPie.csproj.user
  HunterPie/Languages/en-us.xml
  HunterPie/MainWindow.xaml
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, UI, account

#234 Fix(UI): Fix Activities widget
  Docs/_posts/2022-10-10-account.md
  Docs/_posts/2022-10-10-saves-backup.md
  HunterPie.Core/Game/Rise/Definitions/MHRCohootStructure.cs
  HunterPie.Core/Game/Rise/Entities/Activities/MHRCohoot.cs
  HunterPie.Core/Game/Rise/Entities/Activities/MHRMeowmasters.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Activities/Rise/CohootContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Activities/Rise/MeowcenariesContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Activities/View/CohootNestView.xaml
  HunterPie.UI/Overlay/Widgets/Activities/ViewModel/CohootNestViewModel.cs
  HunterPie.UI/Overlay/Widgets/Activities/ViewModel/MockActivitiesViewModel.cs
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, UI

#235 Docs: v2.4.0 patch notes
  Docs/_posts/2022-10-12-update-v2.4.0.md
Labels: documentation

#236 Feat(UI): Add SpookyPie seasonal theme
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/HunterPie.UI.csproj.user
  HunterPie.UI/Resources/Colors.xaml
  HunterPie.UI/Resources/Icons.xaml
  HunterPie.UI/Resources/Seasons/SpookyPie.xaml
  HunterPie.UI/Resources/Styles.xaml
  HunterPie/App.xaml
  HunterPie/MainWindow.xaml
  HunterPie/Properties/AssemblyInfo.cs
Labels: UI

#229 Feat(Localization): Update for v2.4.0
  HunterPie.UI/Controls/Settings/SettingElementHost.xaml
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/ko-kr.xml
Labels: Localization

#239 Feat(Localization): Updated ja-jp for v2.4.0
  HunterPie/Languages/ja-jp.xml
Labels: Localization

#222 Feat(UI): Hide Wirebugs widget while cutscene
  HunterPie.Core/Game/Rise/MHRGame.cs
  HunterPie/Address/MonsterHunterRise.12.0.0.0.map
Labels: enhancement, UI, Rise

#246 Feat(Account): Add forgot password button
  HunterPie.Core/API/Entities/ChangePasswordRequest.cs
  HunterPie.Core/API/Entities/ErrorCode.cs
  HunterPie.Core/API/Entities/PasswordChangeResponse.cs
  HunterPie.Core/API/Entities/PasswordResetRequest.cs
  HunterPie.Core/API/PoogieApi.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Resources/Icons.xaml
  HunterPie.UI/Resources/Styles.xaml
  HunterPie/GUI/Parts/Account/ViewModels/AccountLoginFlowViewModel.cs
  HunterPie/GUI/Parts/Account/ViewModels/AccountPasswordResetFlowViewModel.cs
  HunterPie/GUI/Parts/Account/Views/AccountLoginFlowView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountLoginFlowView.xaml.cs
  HunterPie/GUI/Parts/Account/Views/AccountPasswordResetFlowView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountPasswordResetFlowView.xaml.cs
  HunterPie/HunterPie.csproj.user
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, core, UI, account

#248 Feat(CI): Add Localization file validation pipeline
  .github/workflows/localization-validation.yaml
  Scripts/pipeline/localization/localization_verification.py
  Scripts/pipeline/localization/requirements.txt
  Scripts/v1-abnormality-data-to-v2.py
Labels: chore

#250 Feat(Core): Check if user can upload backup
  HunterPie.Core/API/Entities/CanUploadBackupResponse.cs
  HunterPie.Core/API/PoogieApi.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Features/Backups/GameSaveBackupService.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, account

#259 Fix(Core): Fix Qurio capture indicator
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/Game/Rise/Entities/Monster/MonsterType.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Address/MonsterHunterRise.12.0.1.1.map
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, Rise

#261 Fix(Core): Fixed submarine total item count miscalculation
  HunterPie.Core/Game/Rise/Definitions/MHRSubmarineItemStructure.cs
  HunterPie.Core/Game/Rise/Entities/MHRPlayer.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, core, Rise

#264 Feat(UI): Remote SpookyPie season theme
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/App.xaml
  HunterPie/MainWindow.xaml
  HunterPie/Properties/AssemblyInfo.cs
Labels: UI

#266 Feat(UI): Qurio monster icons
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Architecture/Images/ImageMergerService.cs
  HunterPie.UI/Assets/Monsters/Masks/qurio_mask.png
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/BossMonsterViewModel.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, UI

#265 Feat(UI|Core): Added QuestLife count
  HunterPie.Core/Game/Demos/Sunbreak/MHRSunbreakDemoGame.cs
  HunterPie.Core/Game/IGame.cs
  HunterPie.Core/Game/Rise/MHRGame.cs
  HunterPie.Core/Game/World/MHWGame.cs
  HunterPie.UI/Architecture/Converters/MaxDeathsToVisibilityConverter.cs
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Damage/View/MeterView.xaml
  HunterPie.UI/Overlay/Widgets/Damage/ViewModels/MeterViewModel.cs
  HunterPie/Address/MonsterHunterRise.12.0.1.1.map
Labels: core, UI

#267 Feat(Core): MHR Qurio threshold
  HunterPie.Core/Domain/Interfaces/IUpdatable.cs
  HunterPie.Core/Extensions/IEnumerableExtensions.cs
  HunterPie.Core/Game/Rise/Definitions/MHRQurioThresholdStructure.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonsterPart.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Architecture/ViewModel.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/MonsterWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MockBossMonsterViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterAilmentView.xaml
  HunterPie/Address/MonsterHunterRise.12.0.1.1.map
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, Rise
