Repository HunterPie/HunterPie, pull requests merged in 2022-09, with the labels that each got.

#187 Feat(Core): Add MHW capture data and weaknesses
  HunterPie.Core/Game/Data/MonsterData.cs
  HunterPie.Core/Game/Data/Schemas/MonsterDataSchema.cs
  HunterPie.Core/Game/World/Entities/MHWMonster.cs
  HunterPie/Game/World/Data/MonsterData.xml
Labels: enhancement, World

#186 Chore(Native): Rectify the usage of precompiled header
  .gitignore
  HunterPie.Native/Core/Interfaces/IInitializable.h
  HunterPie.Native/Core/Managers/Damage/manager.cpp
  HunterPie.Native/Core/Managers/Damage/manager.h
  HunterPie.Native/Core/Server/Handlers/Damage/DamageMessageHandler.cpp
  HunterPie.Native/Core/Server/Handlers/Damage/DamageMessageHandler.h
  HunterPie.Native/Core/Server/Handlers/Initialize/InitializationMessageHandler.cpp
  HunterPie.Native/Core/Server/Handlers/MessageHandler.cpp
  HunterPie.Native/Core/Server/IPCService.cpp
  HunterPie.Native/Core/Server/IPCService.h
  HunterPie.Native/Core/Server/Models/Messages.h
  HunterPie.Native/Games/Rise/Common/Monster.h
  HunterPie.Native/Games/Rise/Damage/damage.h
  HunterPie.Native/Games/Rise/Damage/hooks.cpp
  HunterPie.Native/Games/Rise/Damage/hooks.h
  HunterPie.Native/Games/Rise/Utils/RiseUtils.cpp
  HunterPie.Native/HunterPie.Native.vcxproj
  HunterPie.Native/framework.h
  HunterPie.Native/pch.h
Labels: chore

#185 Traditional Chinese for v2.3.0.133 by Jarvis#9491
  HunterPie/Languages/zh-tw.xml
Labels: Localization

#188 Chore(Native): Use nested namespace declarations
  HunterPie.Native/Core/Entities/damage.h
  HunterPie.Native/Core/Managers/Damage/manager.h
  HunterPie.Native/Core/Server/Handlers/Damage/DamageMessageHandler.h
  HunterPie.Native/Core/Server/Handlers/Initialize/InitializationMessageHandler.h
  HunterPie.Native/Core/Server/Handlers/MessageHandler.h
  HunterPie.Native/Core/Server/IPCService.h
  HunterPie.Native/Core/Server/Models/Messages.h
  HunterPie.Native/Games/Rise/Common/Monster.h
  HunterPie.Native/Games/Rise/Damage/damage.h
  HunterPie.Native/Games/Rise/Damage/hooks.h
  HunterPie.Native/Games/Rise/Utils/RiseUtils.h
Labels: chore

#189 Fix(Core): Loading incorrect theme settings
  HunterPie/Internal/Initializers/CustomThemeInitializer.cs
Labels: bug

#192 Fix(Core): Fix to check valid theme path
  HunterPie/Internal/Initializers/CustomThemeInitializer.cs
Labels: bug

#191 Feat(Localization): Added localization for Activities widget
  HunterPie.UI/Overlay/Widgets/Activities/View/CohootNestView.xaml
  HunterPie.UI/Overlay/Widgets/Activities/View/MeowcenariesView.xaml
  HunterPie.UI/Overlay/Widgets/Activities/View/TrainingDojoView.xaml
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/ko-kr.xml
Labels: enhancement

#198 Feat(Core): Add user account
  HunterPie.UI/Architecture/View.cs
  HunterPie.UI/Controls/Buttons/Button.xaml
  HunterPie.UI/Controls/Buttons/Button.xaml.cs
  HunterPie.UI/Controls/Misc/Badge.xaml
  HunterPie.UI/Controls/Misc/Badge.xaml.cs
  HunterPie.UI/Controls/Settings/SettingHost.xaml
  HunterPie.UI/Controls/TextBox/SearchTextBox.xaml
  HunterPie.UI/Controls/TextBox/SearchTextBox.xaml.cs
  HunterPie.UI/Dialog/DialogView.xaml
  HunterPie.UI/Overlay/Controls/Bar.xaml.cs
  HunterPie.UI/Resources/Icons.xaml
  HunterPie.UI/Resources/Styles.xaml
  HunterPie/GUI/Parts/Account/View/AccountView.xaml
  HunterPie/GUI/Parts/Account/ViewModels/AccountViewModel.cs
  HunterPie/GUI/Parts/Account/Views/AccountPreferencesView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountPreferencesView.xaml.cs
  HunterPie/GUI/Parts/Account/Views/AccountView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountView.xaml.cs
  HunterPie/GUI/Parts/HeaderBar.xaml
  HunterPie/GUI/Parts/Sidebar/SideBarContainer.xaml
  HunterPie/GUI/Parts/Sidebar/SideBarContainer.xaml.cs
  HunterPie/HunterPie.csproj
  HunterPie/HunterPie.csproj.user
  HunterPie/MainWindow.xaml
  HunterPie/MainWindow.xaml.cs
Labels: enhancement, core

#197 Feat(Core|UI): Add global notifications
  HunterPie.Core/API/Entities/NotificationType.cs
  HunterPie.Core/API/PoogieApi.cs
  HunterPie.Core/API/Schemas/Notification.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Controls/Buttons/Button.xaml
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Resources/Icons.xaml
  HunterPie/GUI/Parts/HeaderBar.xaml
  HunterPie/GUI/Parts/HeaderBar.xaml.cs
  HunterPie/GUI/Parts/HeaderBarViewModel.cs
  HunterPie/GUI/Parts/Notifications/ViewModels/NotificationViewModel.cs
  HunterPie/GUI/Parts/Notifications/ViewModels/NotificationsPanelViewModel.cs
  HunterPie/GUI/Parts/Notifications/Views/NotificationView.xaml
  HunterPie/GUI/Parts/Notifications/Views/NotificationView.xaml.cs
  HunterPie/GUI/Parts/Notifications/Views/NotificationsPanelView.xaml
  HunterPie/GUI/Parts/Notifications/Views/NotificationsPanelView.xaml.cs
  HunterPie/GUI/ViewModels/MainViewModel.cs
  HunterPie/HunterPie.csproj
  HunterPie/HunterPie.csproj.user
  HunterPie/MainWindow.xaml
  HunterPie/MainWindow.xaml.cs
Labels: enhancement, core

#202 Feat(Core): Track MHR carts counter
  HunterPie.Core/Game/Rise/MHRGame.cs
  HunterPie/Address/MonsterHunterRise.11.0.2.0.map
Labels: core, Rise

#201 Feat(Localization):Added localization for dialog windows
  HunterPie.UI/Controls/Settings/Custom/AbnormalityTrayList.xaml.cs
  HunterPie.UI/Dialog/DialogView.xaml
  HunterPie/Languages/de-de.xml
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/es-mx.xml
  HunterPie/Languages/fr-fr.xml
  HunterPie/Languages/it-it.xml
  HunterPie/Languages/ja-jp.xml
  HunterPie/Languages/ko-kr.xml
  HunterPie/Languages/ru-ru.xml
  HunterPie/Languages/zh-cn.xml
  HunterPie/Languages/zh-tw.xml
  HunterPie/MainWindow.xaml.cs
  HunterPie/Update/UpdateUseCase.cs
Labels: UI, Localization

#204 Feat(Core): Add register and login
  HunterPie.Core/API/Entities/LoginRequest.cs
  HunterPie.Core/API/Entities/LoginResponse.cs
  HunterPie.Core/API/PoogieApi.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Architecture/View.cs
  HunterPie.UI/Controls/Buttons/TabItem.xaml
  HunterPie.UI/Controls/TextBox/SecretTextBox.xaml
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Resources/Styles.xaml
  HunterPie/App.xaml.cs
  HunterPie/GUI/Parts/Account/ViewModels/AccountSignFlowViewModel.cs
  HunterPie/GUI/Parts/Account/ViewModels/AccountViewModel.cs
  HunterPie/GUI/Parts/Account/Views/AccountSignFlowView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountSignFlowView.xaml.cs
  HunterPie/GUI/Parts/Account/Views/AccountView.xaml
  HunterPie/GUI/Parts/Account/Views/AccountView.xaml.cs
  HunterPie/HunterPie.csproj
  HunterPie/HunterPie.csproj.user
  HunterPie/MainWindow.xaml
  HunterPie/MainWindow.xaml.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, core

#203 Refactor(HunterPie): Implement IContextInitializer by game instead of by feature/aspect
  HunterPie.Core/Domain/Memory/IMemoryWriter.cs
  HunterPie.Core/System/Windows/Memory/WindowsMemory.cs
  HunterPie.Core/System/Windows/Native/Kernel32.cs
  HunterPie/App.xaml.cs
  HunterPie/Domain/Interfaces/IContextInitializer.cs
  HunterPie/Features/ContextInitializers.cs
  HunterPie/Features/Native/IPCInjectorInitializer.cs
  HunterPie/Features/Native/NativeIPCInitializer.cs
  HunterPie/Features/Overlay/WirebugWidgetInitializer.cs
  HunterPie/Features/Patcher/GamePatchers.cs
  HunterPie/Features/Patcher/RiseIntegrityPatcher.cs
  HunterPie/Game/Demos/Sunbreak/MHRSunbreakDemoContextInitializer.cs
  HunterPie/Game/Rise/MHRContextInitializer.cs
  HunterPie/Game/World/MHWContextInitializer.cs
Labels: enhancement, core

#205 Chore(All): Cleanup and code analysis suggestions
  .editorconfig
  .github/workflows/pull-request.yaml
  HunterPie.Core.Tests/Address/Map/AddressMapTest.cs
  HunterPie.Core.Tests/Address/Map/AddressMapTokenizerTest.cs
  HunterPie.Core.Tests/Domain/Features/TestFeatureFlagManager.cs
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/API/Entities/Notification.cs
  HunterPie.Core/Address/Map/AddressMap.cs
  HunterPie.Core/Client/Localization/Localization.cs
  HunterPie.Core/Domain/ScanManager.cs
  HunterPie.Core/Game/Data/MonsterData.cs
  HunterPie.Core/Game/Rise/MHRGame.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Core/Input/Hotkey.cs
  HunterPie.Core/Json/JsonProvider.cs
  HunterPie.Core/Native/IPC/Handlers/MessageHandlerManager.cs
  HunterPie.Core/Native/IPC/IPCService.cs
  HunterPie.Core/Remote/CDN.cs
  HunterPie.Core/System/Windows/WindowsProcessManager.cs
  HunterPie.Memory/Core/Signatures.cs
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/Controls/Buttons/ColorPicker.xaml.cs
  HunterPie.UI/Controls/Settings/ViewModel/SettingHostViewModel.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Components/WidgetBase.xaml.cs
  HunterPie.UI/Overlay/Widgets/Activities/Rise/CohootContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Activities/Rise/SubmarinesContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Activities/Rise/TrainingDojoContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Metrics/ViewModel/TelemetricsViewModel.cs
  HunterPie/Features/ContextInitializers.cs
  HunterPie/Features/Overlay/ActivitiesWidgetInitializer.cs
  HunterPie/Features/Overlay/WidgetInitializers.cs
  HunterPie/HunterPie.csproj
  HunterPie/Internal/InitializerManager.cs
  HunterPie/Internal/Initializers/ClientConfigMigrationInitializer.cs
  HunterPie/Internal/Initializers/CustomFontsInitializer.cs
  HunterPie/Internal/Logger/NativeLogger.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: chore

#194 Feat(Native|Core|UI) Show local player's DPS in MHW expeditions
  HunterPie.Core/Client/Configuration/ClientConfig.cs
  HunterPie.Core/Domain/ScannableMethod.cs
  HunterPie.Core/Extensions/UIntExtensions.cs
  HunterPie.Core/Game/Context.cs
  HunterPie.Core/Game/Demos/Sunbreak/MHRSunbreakDemoContext.cs
  HunterPie.Core/Game/World/Entities/MHWPlayer.cs
  HunterPie.Core/Game/World/Entities/Party/MHWParty.cs
  HunterPie.Core/Game/World/Entities/Party/MHWPartyMember.cs
  HunterPie.Core/Game/World/MHWContext.cs
  HunterPie.Core/Game/World/MHWGame.cs
  HunterPie.Core/Native/IPC/Handlers/Internal/Initialiaze/IPCInitializationMessageHandler.cs
  HunterPie.Core/Native/IPC/Handlers/Internal/Initialiaze/Models/IPCInitializationHostType.cs
  HunterPie.Core/Native/IPC/Handlers/Internal/Initialiaze/Models/RequestIPCInitializationMessage.cs
  HunterPie.Core/Native/IPC/Handlers/Internal/Initialiaze/Models/ResponseIPCInitializationMessage.cs
  HunterPie.Core/Native/IPC/Models/IPCMessageType.cs
  HunterPie.Native/Core/Entities/damage.h
  HunterPie.Native/Core/Interfaces/IInitializable.h
  HunterPie.Native/Core/Managers/Damage/manager.cpp
  HunterPie.Native/Core/Managers/Damage/manager.h
  HunterPie.Native/Core/Server/Handlers/Initialize/InitializationMessageHandler.cpp
  HunterPie.Native/Core/Server/Handlers/Initialize/InitializationMessageHandler.h
  HunterPie.Native/Core/Utils/addresses.h
  HunterPie.Native/Games/Rise/Damage/hooks.cpp
  HunterPie.Native/Games/Rise/Damage/hooks.h
  HunterPie.Native/Games/World/Common/Monster.h
  HunterPie.Native/Games/World/Damage/Hooks.cpp
  HunterPie.Native/Games/World/Damage/Hooks.h
  HunterPie.Native/Games/World/Utils/WorldUtils.cpp
  HunterPie.Native/Games/World/Utils/WorldUtils.h
  HunterPie.Native/HunterPie.Native.vcxproj
  HunterPie.Native/HunterPie.Native.vcxproj.filters
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie/Address/MonsterHunterWorld.421471.map
  HunterPie/Features/Native/IPCInjectorInitializer.cs
  HunterPie/Features/Native/NativeIPCInitializer.cs
  HunterPie/Features/Patcher/PatchHelper.cs
  HunterPie/Features/Patcher/WorldIntegrityPatcher.cs
  HunterPie/Game/Rise/MHRContextInitializer.cs
  HunterPie/Game/World/MHWContextInitializer.cs
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/zh-cn.xml
Labels: core, World

#213 Fix: Track expeditions solo damage
  .editorconfig
  HunterPie.Core/Extensions/IntExtensions.cs
  HunterPie.Core/Game/IGame.cs
  HunterPie.Core/Game/Rise/MHRGame.cs
  HunterPie.Core/Game/TimeElapsedChangeEventArgs.cs
  HunterPie.Core/Game/World/Entities/MHWPlayer.cs
  HunterPie.Core/Game/World/Entities/Party/MHWParty.cs
  HunterPie.Core/Game/World/MHWGame.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie/Address/MonsterHunterWorld.421471.map
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug

#214 Fix: Fixed Wirebug abnormalities
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Game/Rise/Data/AbnormalityData.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug

#215 Fix: Fixed party scanning for MHW
  HunterPie.Core/Game/World/Definitions/MHWPartyMemberStructure.cs
  HunterPie.Core/Game/World/Entities/MHWPlayer.cs
  HunterPie.Core/Game/World/MHWGame.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Address/MonsterHunterWorld.421471.map
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug

#217 Feat(Core): Support MHR v12.0.0.0
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Address/MonsterHunterRise.12.0.0.0.map
  HunterPie/Game/Rise/Data/MonsterData.xml
  HunterPie/HunterPie.csproj
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, Rise

#218 Fix(Data): Mapped new monsters
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Native/Games/Rise/Common/Monster.h
  HunterPie.Native/Games/Rise/Utils/RiseUtils.cpp
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Game/Rise/Data/AbnormalityData.xml
  HunterPie/Game/Rise/Data/MonsterData.xml
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: core
