Repository HunterPie/HunterPie, pull requests merged in 2022-07, with the labels that each got.

#102 Feat(Localization): Add Sunbreak monsters in german
  HunterPie/Languages/de-de.xml
Labels: Localization

#101 Feat(Core): Add support for Monster Hunter Rise: Sunbreak
  HunterPie.Core/Client/ClientConfig.cs
  HunterPie.Core/Client/ConfigHelper.cs
  HunterPie.Core/Client/ConfigManager.cs
  HunterPie.Core/Client/Configuration/Versions/V3Config.cs
  HunterPie.Core/Game/Client/IAbnormality.cs
  HunterPie.Core/Game/Data/AbnormalityData.cs
  HunterPie.Core/Game/Data/Schemas/AbnormalitySchema.cs
  HunterPie.Core/Game/Rise/Definitions/MHRChatMessageStructure.cs
  HunterPie.Core/Game/Rise/Entities/MHRConsumableAbnormality.cs
  HunterPie.Core/Game/Rise/Entities/MHRDebuffAbnormality.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/Game/Rise/Entities/MHRPlayer.cs
  HunterPie.Core/Game/Rise/Entities/MHRSongAbnormality.cs
  HunterPie.Core/Game/Rise/MHRGame.cs
  HunterPie.Core/Game/World/Entities/Abnormalities/MHWAbnormality.cs
  HunterPie.Core/Http/PoogieBuilder.cs
  HunterPie.Core/Http/PoogieResponse.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Core/Json/JsonProvider.cs
  HunterPie.Core/System/Windows/MHRProcessManager.cs
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.Memory/Program.cs
  HunterPie.UI/Architecture/ClickableControl.cs
  HunterPie.UI/Architecture/Converters/TestMultibinding.cs
  HunterPie.UI/Controls/Settings/Custom/Abnormality/AbnormalitiesViewHelper.cs
  HunterPie.UI/Controls/Settings/SettingHost.xaml
  HunterPie.UI/Controls/Settings/SettingHost.xaml.cs
  HunterPie.UI/Controls/Settings/ViewModel/SettingHostViewModel.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Abnormality/AbnormalityContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Abnormality/View/AbnormalityBarView.xaml
  HunterPie.UI/Overlay/Widgets/Abnormality/ViewModel/AbnormalityViewModel.cs
  HunterPie.UI/Overlay/Widgets/Abnormality/ViewModel/MockAbnormalityBarViewModel.cs
  HunterPie.UI/Overlay/Widgets/Activities/RiseActivitiesWidgetContextHandler.cs
  HunterPie.UI/Resources/Abnormalities.xaml
  HunterPie/Address/MonsterHunterRise.10.0.2.0.map
  HunterPie/App.xaml.cs
  HunterPie/Features/Overlay/AbnormalitiesWidgetInitializer.cs
  HunterPie/Features/Overlay/WirebugWidgetInitializer.cs
  HunterPie/Features/Patcher/GamePatchers.cs
  HunterPie/Features/Tools/Localization/ViewModels/LocalizableStringViewModel.cs
  HunterPie/Features/Tools/Localization/Views/LocalizableStringView.xaml
  HunterPie/Features/Tools/Localization/Views/LocalizableStringView.xaml.cs
  HunterPie/Game/Rise/Data/AbnormalityData.xml
  HunterPie/Game/Rise/Data/MonsterData.xml
  HunterPie/HunterPie.csproj
  HunterPie/Integrations/Discord/RiseRichPresence.cs
  HunterPie/Internal/Initializers/ClientConfigMigrationInitializer.cs
  HunterPie/Internal/Migrations/Utils/V2ToV3AbnormalityIdsCorrelation.cs
  HunterPie/Internal/Migrations/V3SettingsMigrator.cs
  HunterPie/Languages/de-de.xml
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/ko-kr.xml
  HunterPie/Languages/zh-cn.xml
  HunterPie/Properties/AssemblyInfo.cs
  Scripts/.gitignore
  Scripts/generate_abnormality_id_migrations.py
Labels: core, Rise

#110 update zh-tw.xml
  HunterPie/Languages/zh-tw.xml
Labels: Localization

#109 ko-kr: Added Citadel and Yawning abyss
  HunterPie/Languages/ko-kr.xml
Labels: Localization

#108 Update zh-cn.xml
  HunterPie/Languages/zh-cn.xml
Labels: Localization

#107 Feat(Localization): Add some more german translations
  .gitignore
  HunterPie/Languages/de-de.xml
Labels: Localization

#112 Fix: Added support for Monster Hunter Rise: Sunbreak v10.0.3.0
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Address/MonsterHunterRise.10.0.3.0.map
  HunterPie/HunterPie.csproj
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, Rise

#116 Feat(UI): Configure rendering framerate
  .github/workflows/pull-request.yaml
  HunterPie.Core/Client/Configuration/ClientConfig.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Languages/de-de.xml
  HunterPie/Languages/en-us.xml
  HunterPie/MainWindow.xaml.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, UI

#121 Refactor(UI): Timed visibility class
  HunterPie.UI/Architecture/AutoVisibilityViewModel.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Monster/MonsterAilmentContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/MonsterPartContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MonsterAilmentViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MonsterPartViewModel.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, UI

#123 Hotfix(Data): Fixed Sunbreak monster size multipliers
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Game/Rise/Data/MonsterData.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, Rise

#124 Feat(UI): Optimize widgets transparency
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Controls/Settings/Custom/AbnormalityWidgetConfigWindow.xaml
  HunterPie.UI/Dialog/DialogView.xaml
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Components/WidgetBase.xaml
  HunterPie.UI/Resources/Styles.xaml
  HunterPie/HunterPie.csproj.user
  HunterPie/MainWindow.xaml
  HunterPie/Properties/AssemblyInfo.cs
  HunterPie/TestWindow.xaml
  HunterPie/TestWindow.xaml.cs
  HunterPie/Update/Presentation/UpdateView.xaml
Labels: UI

#126 Chore: Create LICENSE
  LICENSE
Labels: documentation

#125 Feat(Core|UI): Added MHR monster weaknesses
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/Game/Data/MonsterData.cs
  HunterPie.Core/Game/Data/Schemas/MonsterDataSchema.cs
  HunterPie.Core/Game/Demos/Sunbreak/Entities/Monster/MHRSunbreakDemoMonster.cs
  HunterPie.Core/Game/Enums/Element.cs
  HunterPie.Core/Game/Environment/IMonster.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/Game/World/Entities/MHWMonster.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/Architecture/Converters/ElementToIconConverter.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/HunterPie.UI.csproj.user
  HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/BossMonsterViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/DesignModeViewModels.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MockBossMonsterViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MockMonstersViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterView.xaml
  HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterWeaknessView.xaml
  HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterWeaknessView.xaml.cs
  HunterPie/Game/Rise/Data/MonsterData.xml
  HunterPie/Game/World/Data/MonsterData.xml
  HunterPie/Properties/AssemblyInfo.cs
  Scripts/v1-monster-data-to-v2.py
Labels: enhancement, core, UI, Rise, World

#127 Hotfix(Data): Fixed Furious Rajang silver crown multiplier
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Game/Rise/Data/MonsterData.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, Rise

#128 Feat(UI|Core): DPS relative to join
  HunterPie.Core/Client/Configuration/Enums/DPSCalculationStrategy.cs
  HunterPie.Core/Client/Configuration/Overlay/DamageMeterWidgetConfig.cs
  HunterPie.Core/Game/Rise/Entities/MHRPlayer.cs
  HunterPie.Core/Game/Rise/Entities/Party/MHRParty.cs
  HunterPie.Core/Game/Rise/Utils/MHRiseUtils.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Native/Core/Server/Handlers/Initialize/InitializationMessageHandler.cpp
  HunterPie.Native/Games/Rise/Common/Monster.h
  HunterPie.Native/Games/Rise/Damage/damage.h
  HunterPie.Native/Games/Rise/Damage/hooks.cpp
  HunterPie.Native/Games/Rise/Damage/hooks.h
  HunterPie.Native/Games/Rise/Utils/RiseUtils.h
  HunterPie.Native/HunterPie.Native.vcxproj
  HunterPie.Native/HunterPie.Native.vcxproj.filters
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Damage/MemberInfo.cs
  HunterPie/HunterPie.csproj.user
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, core, UI, Rise

#129 Fix(Core): Unicode DLL injection
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Core/System/Windows/Memory/WindowsMemory.cs
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/HunterPie.UI.csproj
Labels: bug, core

#131 Fix(Localization): Missing monster part names
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Game/World/Data/MonsterData.xml
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, Localization

#132 Fix(Core): Fix unmanaged memory stream leak
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/Assets/Fonts/WorkSans-ExtraLight.ttf
  HunterPie.UI/Assets/Fonts/WorkSans-Light.ttf
  HunterPie.UI/Assets/Fonts/WorkSans-Medium.ttf
  HunterPie.UI/Assets/Fonts/WorkSans-SemiBold.ttf
  HunterPie.UI/Assets/Fonts/WorkSans.ttf
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Components/WidgetBase.xaml
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Damage/MemberInfo.cs
  HunterPie.UI/Overlay/Widgets/Damage/View/MeterView.xaml
  HunterPie.UI/Overlay/Widgets/Damage/View/MeterView.xaml.cs
  HunterPie.UI/Overlay/Widgets/Damage/View/PlayerDamageView.xaml
  HunterPie.UI/Overlay/Widgets/Damage/ViewModels/MeterViewModel.cs
  HunterPie.UI/Overlay/Widgets/Damage/ViewModels/MockMeterViewModel.cs
  HunterPie.UI/Overlay/Widgets/Damage/ViewModels/PlayerViewModel.cs
  HunterPie.UI/Resources/Styles.xaml
  HunterPie.sln
  HunterPie/Features/Debug/DamageWidgetMocker.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, core, UI

#133 Update solution to target NET 6
  Docs/_posts/2022-02-16-faq.md
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/HunterPie.csproj
  HunterPie/Properties/PublishProfiles/FolderProfile.pubxml
  README.md
Labels: chore

#135 Fix(Core): Fixed Enrage structure for MHR
  HunterPie.Core/Game/Rise/Definitions/MHREnrageStructure.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, core, Rise

#136 Feat(Core|UI): Added monster capture indicator
  HunterPie.Core/Game/Demos/Sunbreak/Entities/Monster/MHRSunbreakDemoMonster.cs
  HunterPie.Core/Game/Environment/IMonster.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie.Core/Game/World/Entities/MHWMonster.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Native/HunterPie.Native.vcxproj
  HunterPie.UI/Architecture/Converters/PercentageToLeftMargingDistanceConverter.cs
  HunterPie.UI/Architecture/Extensions/ObjectExtensions.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/BossMonsterViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/ViewModels/MockMonstersViewModel.cs
  HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterView.xaml
  HunterPie.UI/Resources/Icons.xaml
  HunterPie/Address/MonsterHunterRise.10.0.3.0.map
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, core, UI, Rise

#137 Feat(Localization): Added localization for Enums
  HunterPie.Core/Client/Configuration/Enums/DPSCalculationStrategy.cs
  HunterPie.Core/Client/Configuration/Enums/DamagePlotStrategy.cs
  HunterPie.Core/Client/Configuration/Enums/LogLevel.cs
  HunterPie.Core/Client/Configuration/Enums/Orientation.cs
  HunterPie.Core/Client/Configuration/Enums/SortBy.cs
  HunterPie.Core/Client/Localization/Localization.cs
  HunterPie.Core/Client/Localization/LocalizationAttribute.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Architecture/Converters/EnumToStringConverter.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Resources/Styles.xaml
  HunterPie.UI/Settings/Internal/EnumVisualConverter.cs
  HunterPie.UI/Settings/VisualConverterManager.cs
  HunterPie/HunterPie.csproj
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: core, Localization

#138 Feat(Integrations): Display Master Rank in Discord's RPC
  HunterPie.Core/Game/Client/IPlayer.cs
  HunterPie.Core/Game/Demos/Sunbreak/Entities/Player/MHRSunbreakDemoPlayer.cs
  HunterPie.Core/Game/Rise/Definitions/MHRPlayerLevelStructure.cs
  HunterPie.Core/Game/Rise/Entities/MHRPlayer.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Integrations/Discord/RiseRichPresence.cs
  HunterPie/Languages/en-us.xml
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, core, Integrations

#141 Fix(UI): Fixed MHW widgets not closing properly
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/WidgetManager.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, UI

#142 Docs: v2.2.0 patch notes
  Docs/_posts/2022-06-14-damage-meter-widget.md
  Docs/_posts/2022-07-20-update-v2.2.0.md
Labels: documentation

#143 ko-kr for v2.2.0
  HunterPie/Languages/en-us.xml
  HunterPie/Languages/ko-kr.xml
Labels: Localization

#140 v2.2.0 French translation
  HunterPie/Languages/fr-fr.xml
Labels: Localization

#120 file update by Jarvis#9491 in HunterPie Discord translations channel
  HunterPie/Languages/zh-tw.xml
Labels: Localization

#119 Update zh-cn.xml
  HunterPie/Languages/zh-cn.xml
Labels: Localization

#147 ja-jp loc update
  HunterPie/Languages/ja-jp.xml
Labels: Localization

#152 Feat(Data): Add Rise support for “Shock Trap” and “Pitfall Trap”
  HunterPie/Game/Rise/Data/MonsterData.xml
Labels: enhancement, Rise
