Repository HunterPie/HunterPie, pull requests merged in 2022-12, with the labels that each got.

#313 Hotfix: Fixed most common exceptions not being handled by HunterPie
  HunterPie.UI/Architecture/Converters/SecondsToTimeString.cs
  HunterPie.UI/Overlay/Controls/Bar.xaml.cs
  HunterPie.UI/Overlay/Widgets/Monster/Views/BossMonsterAilmentView.xaml
  HunterPie/App.xaml.cs
  HunterPie/GUI/Parts/Account/ViewModels/AccountRegisterFlowViewModel.cs
Labels: bug

#314 Feat(UI): WinterPie
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/HunterPie.UI.csproj.user
  HunterPie.UI/Resources/Seasons/WinterPie.xaml
  HunterPie/App.xaml
  HunterPie/HunterPie.csproj
  HunterPie/HunterPie.csproj.user
  HunterPie/MainWindow.xaml
  HunterPie/MainWindow.xaml.cs
  HunterPie/Properties/AssemblyInfo.cs
  HunterPie/Resources/Styles/Client.xaml
Labels: enhancement

#326 Feat(Core|Data): Support for infinite debuff and Leeched debuff for RIse
  HunterPie.Core/Game/Data/AbnormalityData.cs
  HunterPie.Core/Game/Data/Schemas/AbnormalitySchema.cs
  HunterPie.Core/Game/Enums/AbnormalityCompareType.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRDebuffAbnormality.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRPlayer.cs
  HunterPie.UI/Resources/Abnormalities.xaml
  HunterPie/Game/Rise/Data/AbnormalityData.xml
Labels: scope: core, scope: data
