Repository HunterPie/HunterPie, pull requests merged in 2022-11, with the labels that each got.

#260 Feat(UI): Add patch notes view
  HunterPie.Core/API/Entities/PatchResponse.cs
  HunterPie.Core/API/PoogieApi.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/Controls/Buttons/BannerCard.xaml
  HunterPie.UI/Controls/Buttons/BannerCard.xaml.cs
  HunterPie.UI/Controls/Buttons/Skeleton/BannerCardSkeleton.xaml
  HunterPie.UI/Controls/Buttons/Skeleton/BannerCardSkeleton.xaml.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/HunterPie.UI.csproj.user
  HunterPie.UI/Resources/Icons.xaml
  HunterPie/Domain/Sidebar/ISideBar.cs
  HunterPie/Domain/Sidebar/SideBar.cs
  HunterPie/GUI/Parts/Patches/ViewModels/PatchViewModel.cs
  HunterPie/GUI/Parts/Patches/ViewModels/PatchesViewModel.cs
  HunterPie/GUI/Parts/Patches/Views/PatchesView.xaml
  HunterPie/GUI/Parts/Patches/Views/PatchesView.xaml.cs
  HunterPie/GUI/Parts/Sidebar/Service/SideBarService.cs
  HunterPie/GUI/Parts/Sidebar/SideBarContainer.xaml
  HunterPie/GUI/Parts/Sidebar/SideBarContainer.xaml.cs
  HunterPie/GUI/Parts/Sidebar/SideBarElement.xaml.cs
  HunterPie/GUI/Parts/Sidebar/ViewModels/PatchNotesSideBarElementViewModel.cs
  HunterPie/HunterPie.csproj.user
  HunterPie/Internal/InitializerManager.cs
  HunterPie/Internal/Initializers/MenuInitializer.cs
  HunterPie/Properties/AssemblyInfo.cs
  HunterPie/Update/UpdateService.cs
  HunterPie/Update/UpdateUseCase.cs
Labels: enhancement, UI

#271 Feat(Core): Infinite buffs support
  HunterPie.Core/Game/Data/AbnormalityData.cs
  HunterPie.Core/Game/Data/Schemas/AbnormalitySchema.cs
  HunterPie.Core/Game/Rise/Entities/MHRConsumableAbnormality.cs
  HunterPie.Core/Game/Rise/Entities/MHRPlayer.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Abnormality/AbnormalityContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Abnormality/View/AbnormalityBarView.xaml
  HunterPie.UI/Overlay/Widgets/Abnormality/ViewModel/AbnormalityViewModel.cs
  HunterPie/Game/Rise/Data/AbnormalityData.xml
  HunterPie/Languages/en-us.xml
  HunterPie/MainWindow.xaml
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, core, Rise

#272 Docs: v2.5.0 patch notes 🚀
  Docs/_posts/2022-02-13-monster-widget.md
  Docs/_posts/2022-10-12-update-v2.5.0.md
Labels: documentation

#255 Feat(Localization): Missed spanish translations, monsters and locations
  HunterPie/Languages/es-mx.xml
Labels: Localization

#245 Feat(Loc): Add a missing string for ko-kr
  HunterPie/Languages/ko-kr.xml
Labels: Localization

#274 Feat(Loc): Update ko-kr for v2.5.0
  HunterPie/Languages/ko-kr.xml
Labels: Localization

#288 Feat(Core|Data): Show capture icon for capturable monsters only (Rise)
  HunterPie.Core/Game/Data/MonsterData.cs
  HunterPie.Core/Game/Data/Schemas/MonsterDataSchema.cs
  HunterPie.Core/Game/Rise/Entities/MHRMonster.cs
  HunterPie/Game/Rise/Data/MonsterData.xml
Labels: enhancement, Rise

#290 Feat(UI): Toggle overlay hotkey
  HunterPie.Core/Client/Configuration/Overlay/OverlayClientConfig.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Components/WidgetBase.xaml
  HunterPie.UI/Overlay/WidgetManager.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: UI

#293 Fix(Core): Fix qurio health
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Integrations/Datasources/MonsterHunterRise/Definitions/MHRQurioPartStructure.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonster.cs
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/GUI/Parts/Backup/ViewModels/BackupsViewModel.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug, scope: core, game: rise

#295 Feat(Core): Added Smart events for detecting event memory leaks
  HunterPie.Core.Tests/HunterPie.Core.Tests.csproj
  HunterPie.Core/Architecture/Collections/ThreadSafeObservableCollection.cs
  HunterPie.Core/Architecture/Events/ISmartEvent.cs
  HunterPie.Core/Architecture/Events/SmartEvent.cs
  HunterPie.Core/Architecture/Events/SmartEventsTracker.cs
  HunterPie.Core/Domain/Scannable.cs
  HunterPie.Core/Extensions/IDispatchableExtensions.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Chat/MHRChat.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonster.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonsterAilment.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonsterPart.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Environment/Activities/MHRArgosy.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Environment/Activities/MHRCohoot.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Environment/Activities/MHRMeowmasters.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Environment/Activities/MHRSubmarine.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Environment/Activities/MHRTrainingDojo.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Environment/NPC/MHRBuddy.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Game/MHRGame.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Party/MHRParty.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Party/MHRPartyMember.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRConsumableAbnormality.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRDebuffAbnormality.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRPlayer.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRSongAbnormality.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/MHRWirebug.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Player/Weapons/MHRMeleeWeapon.cs
  HunterPie.Integrations/Datasources/MonsterHunterSunbreakDemo/Entity/Enemy/MHRSunbreakDemoMonster.cs
  HunterPie.Integrations/Datasources/MonsterHunterSunbreakDemo/Entity/Game/MHRSunbreakDemoGame.cs
  HunterPie.Integrations/Datasources/MonsterHunterSunbreakDemo/Entity/Player/MHRSunbreakDemoPlayer.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Enemy/MHWMonster.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Enemy/MHWMonsterAilment.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Enemy/MHWMonsterPart.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Game/MHWGame.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Party/MHWParty.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Party/MHWPartyMember.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/MHWAbnormality.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/MHWPlayer.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/MHWSpecializedTool.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Player/Weapons/MHWMeleeWeapon.cs
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.Memory/HunterPie.Memory.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/WidgetManager.cs
  HunterPie.UI/Overlay/Widgets/Activities/Rise/MeowcenariesContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Activities/Rise/SubmarinesContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Activities/RiseActivitiesWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Damage/DamageMeterWidgetContextHandler.cs
  HunterPie.UI/Overlay/Widgets/Player/ViewModels/PlayerHudViewModel.cs
  HunterPie.UI/Overlay/Widgets/Wirebug/WirebugWidgetContextHandler.cs
  HunterPie.sln
  HunterPie/App.xaml.cs
  HunterPie/Domain/Sidebar/SideBar.cs
  HunterPie/GUI/Parts/Debug/Views/EventTrackerView.xaml
  HunterPie/GUI/Parts/Debug/Views/EventTrackerView.xaml.cs
  HunterPie/GUI/Parts/Sidebar/ViewModels/DebugSideBarElementViewModel.cs
  HunterPie/HunterPie.csproj
  HunterPie/HunterPie.csproj.user
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, scope: core

#299 Feat(Core): Add memory read cache
  HunterPie.Core/Domain/Cache/Model/ThreadSafeCacheEntry.cs
  HunterPie.Core/Domain/Cache/ThreadSafeMemoryCache.cs
  HunterPie.Core/Domain/Memory/IMemoryCache.cs
  HunterPie.Core/Domain/ScanManager.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Core/System/Windows/Memory/WindowsMemory.cs
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Metrics/View/TelemetricsView.xaml
  HunterPie/Address/MonsterHunterRise.13.0.0.0.map
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement, feat: optimizations

#302 Docs: Added v2.6.0 patch notes :rocket:
  Docs/_posts/2022-11-02-update-v2.5.0.md
  Docs/_posts/2022-11-26-player-hud-widget.md
  Docs/_posts/2022-11-26-update-v2.6.0.md
  Docs/_sass/addon/commons.scss
  Docs/_sass/colors/dark-typography.scss
Labels: documentation

#308 Hotfix(Core): Rollback and remove Memory Cache
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Core/System/Windows/Memory/WindowsMemory.cs
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonster.cs
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Internal/Initializers/HotkeyInitializer.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug
