Repository HunterPie/HunterPie, pull requests merged in 2025-04, with the labels that each got.

#625 fix: clear log on runtime
  HunterPie/Internal/Logger/FileStreamLogWriter.cs
Labels: bug

#630 feat(statistics): add sliding average dps to exported hunts
  HunterPie.Core/Client/Localization/ILocalizationRepository.cs
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.DI/HunterPie.DI.csproj
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.Platforms/HunterPie.Platforms.csproj
  HunterPie.UI/Architecture/Brushes/ColorFadeGradient.cs
  HunterPie.UI/Architecture/Converters/EnumToStringConverter.cs
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Features/Languages/Repository/LocalizationRepository.cs
  HunterPie/Features/Statistics/Details/Builders/PartyMemberDetailsViewModelBuilder.cs
  HunterPie/Features/Statistics/Details/Enums/PlotStrategy.cs
  HunterPie/Features/Statistics/Details/ViewModels/MonsterDetailsViewModel.cs
  HunterPie/Features/Statistics/Details/ViewModels/PartyMemberDetailsViewModel.cs
  HunterPie/Features/Statistics/Details/ViewModels/QuestDetailsViewModel.cs
  HunterPie/Features/Statistics/Details/Views/MonsterDetailsView.xaml
  HunterPie/Features/Statistics/Details/Views/MonsterDetailsView.xaml.cs
  HunterPie/Features/Statistics/Details/Views/QuestDetailsView.xaml
  HunterPie/Features/Statistics/Details/Views/QuestDetailsView.xaml.cs
  HunterPie/Features/Statistics/Views/MonsterSummaryView.xaml
  HunterPie/HunterPie.csproj
  HunterPie/Properties/AssemblyInfo.cs
Labels: enhancement

#634 feat(core): add support for monster breakable & severable parts
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.DI/HunterPie.DI.csproj
  HunterPie.Integrations/Datasources/MonsterHunterWilds/Definitions/Monster/MHWildsMonsterPartData.cs
  HunterPie.Integrations/Datasources/MonsterHunterWilds/Definitions/Monster/MHWildsPartBreak.cs
  HunterPie.Integrations/Datasources/MonsterHunterWilds/Definitions/Monster/MHWildsPartHealth.cs
  HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Enemy/Data/UpdatePartData.cs
  HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Enemy/MHWildsMonster.cs
  HunterPie.Integrations/Datasources/MonsterHunterWilds/Entity/Enemy/MHWildsMonsterPart.cs
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.Platforms/HunterPie.Platforms.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Address/MonsterHunterWilds.1.1.0.0.map
  HunterPie/Properties/AssemblyInfo.cs
Labels: game: wilds

#637 fix(ui): display weakness for monster in older games
  HunterPie.Core/HunterPie.Core.csproj
  HunterPie.Integrations/Datasources/MonsterHunterRise/Entity/Enemy/MHRMonster.cs
  HunterPie.Integrations/Datasources/MonsterHunterWorld/Entity/Enemy/MHWMonster.cs
  HunterPie.Integrations/HunterPie.Integrations.csproj
  HunterPie.Platforms/HunterPie.Platforms.csproj
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie.UI/Overlay/Widgets/Monster/MonsterContextHandler.cs
  HunterPie/Properties/AssemblyInfo.cs
Labels: bug

#640 feat(core): support mhwilds v1.1.1.0
  HunterPie.UI/HunterPie.UI.csproj
  HunterPie/Address/MonsterHunterWilds.1.1.1.0.map
  HunterPie/HunterPie.csproj
  HunterPie/Properties/AssemblyInfo.cs
Labels: game: wilds
